[package]
authors = ["SilverWingedSeraph <lfstindall@gmail.com>"]
name = "mlem-asm"
version = "0.1.0"

[dependencies]
mlem = {git = "https://github.com/SilverWingedSeraph/mlem"}
serde = "^1"
serde_cbor = "^0.5"
serde_derive = "^1"
